### ISSUE TITLE
hello I faced this error and I dont know how to solve it.

### ISSUE THREAD

**Issue by mokems** [SketchyScene/SketchySceneColorization#13]
Traceback (most recent call last):
  File "/content/SketchySceneColorization/Instance_Matching/matching_main.py", line 523, in <module>
    captions_base_dir=args.captions_base_dir)
  File "/content/SketchySceneColorization/Instance_Matching/matching_main.py", line 141, in train
    print('firstly train, loaded', ckpt.model_checkpoint_path)
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by mokems** [comment]
I have downloaded the resnet_pretrained_model and put the files in the diractory named SketchyScene_DeepLabv2

**Comment by mokems** [comment]
>

> 

>

**Comment by mokems** [comment]
I have downloaded the resnet_pretrained_model and put the files in the diractory named SketchyScene_DeepLabv2
